# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{linqr}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["surya"]
  s.date = %q{2011-09-10}
  s.description = %q{Linq like sytax for querying multiple-datasources}
  s.email = %q{surya.gaddipati@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "examples/linqr2enumerable/ordering_operators_spec.rb",
    "examples/linqr2enumerable/projection_operators_spec.rb",
    "lib/expression_evaluator_base.rb",
    "lib/group_by.rb",
    "lib/lazy_enumerator.rb",
    "lib/linqr.rb",
    "lib/linqr_exp.rb",
    "lib/providers/active_record/active_record_expression_evaluator.rb",
    "lib/providers/active_record/activerecord_provider.rb",
    "lib/providers/enumerable_expression_evaluator.rb",
    "lib/providers/enumerable_provider.rb",
    "lib/providers/groupon/groupon_provider.rb",
    "lib/providers/hash_provider.rb",
    "lib/source_name_evaluator.rb",
    "spec/active_record_provider_spec.rb",
    "spec/database.yml",
    "spec/enumerable_expression_evaluator_spec.rb",
    "spec/enumerable_provider_spec.rb",
    "spec/groupon_provider_spec.rb",
    "spec/order.rb",
    "spec/schema.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/suryagaddipati/linqr}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.1}
  s.summary = %q{Query Comprehensions for ruby}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rspec>, ["~> 2.4.0"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rspec>, ["~> 2.4.0"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rspec>, ["~> 2.4.0"])
  end
end

